[tools]
bun = "latest"
deno = "latest"
go = "latest"
jq = "latest"
k3d = "latest"
python = "latest"
quarkus = "3.32.2"
rust = "1.93.1"
usage = "latest"
uv = "latest"
zola = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
experimental = true
